Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 10438
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Container python  Created
Attaching to python
python  |  * Serving Flask app 'server.py'
python  |  * Debug mode: off
python  | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
python  |  * Running on all addresses (0.0.0.0)
python  |  * Running on http://127.0.0.1:5000
python  |  * Running on http://172.18.0.2:5000
python  | [33mPress CTRL+C to quit[0m
python exited with code 137
 * Serving Flask app 'server.py'
 * Debug mode: off
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.2:5000
[33mPress CTRL+C to quit[0m
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Status:	
	machine: minikube
	pid: 48614
	route: 10.96.0.0/12 -> 172.31.46.155
	minikube: Running
	services: [pythonapp-service]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
Unable to find image 'python:latest' locally
latest: Pulling from library/python
Digest: sha256:745efdfb7e4aac9a8422bd8c62d8bc35a693e8979a240d29677cb03e6aa91052
Status: Downloaded newer image for python:latest
Unable to find image 'teodorionascu/python:latest' locally
docker: Error response from daemon: manifest for teodorionascu/python:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
Unable to find image 'teodorionascu/python:latest' locally
docker: Error response from daemon: manifest for teodorionascu/python:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
Unable to find image 'teodorionascu/python:latest' locally
docker: Error response from daemon: manifest for teodorionascu/python:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
Unable to find image 'teodorionascu/python:latest' locally
docker: Error response from daemon: manifest for teodorionascu/python:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
